jobs:
  build:
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
orbs:
  node: circleci/node@1.1
version: 2.1

